FROM node:21 as base

ARG DB_PORT
ARG DB_HOST
ARG DB_NAME
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG CONFIG_PATH

ENV DB_PORT ${DB_PORT}
ENV DB_HOST ${DB_HOST}
ENV DB_NAME ${DB_NAME}
ENV POSTGRES_USER ${POSTGRES_USER}
ENV POSTGRES_PASSWORD ${POSTGRES_PASSWORD}

COPY package.json .
RUN npm install --verbose
COPY ./db ./db
# CMD ls db
#CMD echo ${CONFIG_PATH}
CMD npx drizzle-kit push:pg --config=${CONFIG_PATH}

