version: "3.9"
name: test

services:
  backend:
    hostname: ${BACKEND_HOSTNAME}
    build:
      context: server
      dockerfile: Dockerfile
      target: test
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - PORT=${BACKEND_PORT}
      - NODE_ENV=development
      - LOG_LEVEL=error
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOSTNAME}
      - DB_NAME=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrestest
    volumes:
      - /app/node_modules
    tty: true
    networks:
      - proxynet_test

networks:
  proxynet_test:
    name: db_network_test
